Refactor de Travis
taller2fiuba/hello-world-flask pull request #14
Opened 2020-04-27 23:02 UTC by sportelliluciano

Refactorizo .travis.yml para que sea más claro y fácil de mantener.

2020-04-27 23:56 UTC, FrancoLiberali commented on bin/travis/run-acceptance-tests-on-master-or-pr
> +# - Pull hello-world-node and hello-world-acceptance-tests from their repos
ay dont spik inglish

2020-04-28 00:05 UTC, FrancoLiberali requested changes
menos el ingles creo que esta todo ok. Igual no estoy seguro de estar muy contengo con la eliminacion de los before_install, install,etc, que hacen tener que guadar las salidas de los comandos de tests en variables.

2020-04-28 00:23 UTC, sportelliluciano commented
> menos el ingles creo que esta todo ok. Igual no estoy seguro de estar muy contengo con la eliminacion de los before_install, install,etc, que hacen tener que guadar las salidas de los comandos de tests en variables.

El problema es que esa segregación hace que instales un montón de cosas innecesarias el 80% de las veces. Heroku CLI sólo se usa al deployar; los repos de node, acceptance y sus dependencias sólo se usan en los PR.

2020-04-28 00:29 UTC, FrancoLiberali approved these changes

2020-04-28 00:45 UTC, edjus approved these changes

2020-04-28 00:47 UTC, merged